services:
  bitcoind:
    build: .
    ports:
      - "8332:8332"
    volumes:
      - bitcoin_data:/mnt/data/bitcoin-unique
    restart: unless-stopped
    command: ["bitcoind", "-datadir=/mnt/data/bitcoin-unique"]

volumes:
  bitcoin_data:
